# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2015

# Custom your favicon.ico in `site/source`
favicon: https://avatars.githubusercontent.com/u/3949015?v=4

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: false

# ===========================================
# Menu Settings
# ===========================================
menu:
  首页: /
  # 时间线: /archives/
  标签: /tags/
  # 分类: /categories/
  # 关于: /about/

# ===========================================
# Theme Settings
# ===========================================
# color: default | mint green | cobalt blue | hot pink | dark violet
color: mint green

# default page mode: default | archives
mode: archives

toc: true

# jQuery fancybox
fancybox: true

# LaTeX support (via MathJax)
latex: false

copyright:
  enable: false
  # https://creativecommons.org/
  license: '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>'

reward:
  enable: false
  qrCode:
    wechat:
    alipay:

# ===========================================
# Social links Settings
# ===========================================
social:
  # email: your@email.com
  stack-overflow:
  twitter:
  facebook:
  linkedin:
  google:
  github: https://github.com/nimoc
  weibo:
  zhihu: https://www.zhihu.com/people/nimoc
  douban:
  pocket:
  tumblr:
  instagram:

# ===========================================
# Third Party Services Settings
# ===========================================

# LeanCloud
leancloud:
  app_id:
  app_key:

# Baidu Analytics
baidu_analytics:
# Baidu Verification
baidu_verification:

# Google Analytics
google_analytics:
# Google Verification
google_verification:

# Disqus
disqus_shortname:

#Changyan
changyan:
  appid:
  appkey:

#LiveRe
livere_datauid:

# Gitalk
# Demo: https://gitalk.github.io
# https://github.com/gitalk/gitalk
gitalk:
  enable: false
  github_id: nimoc
  repo: blog
  client_id: f480e03b833fb99192ea
  client_secret: GitHub Application Client Secret
  admin_user: nimoc
  distraction_free_mode: true # Facebook-like distraction free mode
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en, es-ES, fr, ru, zh-CN, zh-TW
  language:

# utterances
# Docs: https://utteranc.es/
# Tips: Make sure you have installed [utterances app](https://github.com/apps/utterances) in your repo
utterances:
  enable: false
  repo: owner/repo # Repository
  issueTerm: title  # Blog post ↔️ issue mapping: pathname | url | title | og:title
  theme: github-light # Theme: github-light | github-dark | github-dark-orange | icy-dark | dark-blue | photon-dark
  label: utterances # Issue label

# ===========================================
# Version
# ===========================================
version: 2.11.0
